# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6452ec99c624ab42a3fb2b745f102d516082e20583af4c58968e987e6461fe384cd487e4d09dea7851e2a0f8cdfd6fddd9bd5822455ca412168477c37d5dc3d3

test:
  secret_key_base: deb85cc52f29cc05ded634a7b7161a9218d7e15df3cff5eb980111059b003169eda37872ddc25fb715c2c341a6682ccaafd76b02f7f4555fd474fa51e05b4409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
